### ISSUE TITLE
why we need to calculate reference_avg and ref_angle?

### ISSUE THREAD

**Issue by szy120320** [michaeldalverson/CrysTens#3]
![微信图片_20230701194218](https://github.com/michaeldalverson/CrysTens/assets/63035867/c1306891-f103-4f49-9ccf-11d17bc5a7e8)

hi, I want to know why we need to compare abs(crys_tens[num, 7, 0] - ref_avg)/ref_avg with  ref_percent. Can you give me a reason?
And I use your diffusion model to generate some crystal strucuture(I use myself dataset), but it always has  weird length and large cell_volume. What'smore, it's  space_group is "P 1" rather than predicted space_group. Thank you.
![11](https://github.com/michaeldalverson/CrysTens/assets/63035867/537130d1-492d-4374-8f3b-43825a4b7dc2)

**Comment by szy120320** [comment]
And I want to know about what the ref_percent does. why we need to set the ref_percent.

**Comment by szy120320** [comment]
@michaeldalverson

**Comment by szy120320** [comment]
I found the parameter(reference_average) is not used later. Do you mean that the originally reference_average was ref_avg but you wrote it wrong?  Thank you.

**Comment by szy120320** [comment]
could you tell me why all generated crystal structure's _symmetry_space_group_name_H-M equal to "P 1"?  In addition, I found that in your post processing, lattice was constructed first, and then Structure class was used to construct the structure, but the input parameters did not use the predicted space group. All the generated cif files have _symmetry_space_group_name_H-M equal to "P1". So here are some question I'd like to ask you. Thank you. @michaeldalverson

**Comment by szy120320** [comment]
> ![微信图片_20230701194218](https://user-images.githubusercontent.com/63035867/250272126-c1306891-f103-4f49-9ccf-11d17bc5a7e8.png)
> 
> hi, I want to know why we need to compare abs(crys_tens[num, 7, 0] - ref_avg)/ref_avg with ref_percent. Can you give me a reason? And I use your diffusion model to generate some crystal strucuture(I use myself dataset), but it always has weird length and large cell_volume. What'smore, it's space_group is "P 1" rather than predicted space_group. Thank you. ![11](https://user-images.githubusercontent.com/63035867/250272496-537130d1-492d-4374-8f3b-43825a4b7dc2.png)

I found that in your post-processing, the conversion of tensors did not use the pre-processing method. I found that the two tensors obtained by using your post-processing method and the method of converting tensors in the pre-processing are not the same, so I found the problem.
![QQ图片20230703232632](https://github.com/michaeldalverson/CrysTens/assets/63035867/3dbde572-740f-4edf-9b9a-4018d96bb20c)

**Comment by szy120320** [comment]
I still can't solve this problem, the symmetry of the crystal structure that I generate is always P1, and I want to know how to generate a crystal structure that has symmetry. I have tried to debug these parameters, including ref_percent, ref_coord_percent, num_coord_clusters, and num_atom_clusters. Can you answer my question? Thank you! @michaeldalverson

**Comment by michaeldalverson** [comment]
Hello @szy120320,

The abs(crys_tens[num, 7, 0] - ref_avg)/ref_avg >= ref_percent line is used to determine when to stop collecting atoms from the CrysTens structure. By default, ref_percent is set to 0.2, so when a given column has a space group number that differs by more than 20% from the average, it uses that as an indication that there are no more atoms to place. For example, if we have a CrysTens with the following space group number predictions in row 7, (200, 202, 201, 198, 10, 5, 0, 0, 0), we should stop after 198 and take the average of the first four numbers. A lower ref_percent would be a stricter parameter and a higher ref_percent would allow for more variability. 

As far as the large cell volume, I am unsure of why that is occurring. How long are you training the diffusion model?

As of now, we do not construct the CIF using the space group number because unless the atoms are perfectly aligned with the expected space group, there can be a lot of overlap and repetition. I can add an option for the construction of CIFs using the space group. However, even with the inclusion of space group, I believe the CIF is still reported to have a space group of P1 which is an artifact of PyMatGen. I can however, look into changing that.

**Comment by szy120320** [comment]
> 

Thank you for you reply. Now, the only problem I have is that the space group of the crystal structure I generated is P1, so it doesn't behave symmetrically very well. The atomic  fractional coordinates in the crystals that I generate are actually very difficult to get symmetric, right? I want to use your model to generate some desired crystal structure. Of course, I believe this is a challenge problem for me. In general, I really appreciate your detailed reply.

**Comment by szy120320** [comment]
Hello, why am I using your data set to train your model, but the symmetry of the crystal structures I produce is P1? How do I generate a crystal whose symmetry is not P1? @michaeldalverson
